on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    name: Release pylunar
    runs-on: ubuntu-latest
    if: github.repository_owner == 'LunarsDev' && github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        run: pip install poetry
      - uses: bjoluc/semantic-release-config-poetry@v2
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
